"""base db

Revision ID: 4eae24858a42
Revises: edf68aae64c2
Create Date: 2025-01-07 23:40:57.409852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from backend.db import JSONEncodedList

# revision identifiers, used by Alembic.
revision: str = '4eae24858a42'
down_revision: Union[str, None] = 'edf68aae64c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('landlord_details', sa.Column('images_list', JSONEncodedList(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('landlord_details', 'images_list')
    # ### end Alembic commands ###
